/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Apr 02 16:31:49 2019. */

#ifndef PB_IMUMSG_PB_H_INCLUDED
#define PB_IMUMSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _IMUInfo {
    bool has_acc_x;
    float acc_x;
    bool has_acc_y;
    float acc_y;
    pb_callback_t sensorID;
    bool has_acc_z;
    float acc_z;
    bool has_angular_x;
    float angular_x;
    bool has_angular_y;
    float angular_y;
    bool has_angular_z;
    float angular_z;
    bool has_time_stamp;
    float time_stamp;
    bool has_isStamp;
    bool isStamp;
    bool has_USensorForward;
    float USensorForward;
    bool has_USensorDownward;
    float USensorDownward;
    pb_callback_t piCamImage;
    bool has_imageWidth;
    int32_t imageWidth;
    bool has_imageHeight;
    int32_t imageHeight;
/* @@protoc_insertion_point(struct:IMUInfo) */
} IMUInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define IMUInfo_init_default                     {false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define IMUInfo_init_zero                        {false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define IMUInfo_time_stamp_tag                   8
#define IMUInfo_isStamp_tag                      9
#define IMUInfo_sensorID_tag                     3
#define IMUInfo_acc_x_tag                        1
#define IMUInfo_acc_y_tag                        2
#define IMUInfo_acc_z_tag                        4
#define IMUInfo_angular_x_tag                    5
#define IMUInfo_angular_y_tag                    6
#define IMUInfo_angular_z_tag                    7
#define IMUInfo_USensorForward_tag               10
#define IMUInfo_USensorDownward_tag              11
#define IMUInfo_piCamImage_tag                   12
#define IMUInfo_imageHeight_tag                  14
#define IMUInfo_imageWidth_tag                   13

/* Struct field encoding specification for nanopb */
extern const pb_field_t IMUInfo_fields[15];

/* Maximum encoded size of messages (where known) */
/* IMUInfo_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define IMUMSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
