/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Apr 02 16:31:49 2019. */

#include "imumsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t IMUInfo_fields[15] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, IMUInfo, acc_x, acc_x, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, acc_y, acc_x, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, IMUInfo, sensorID, acc_y, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, acc_z, sensorID, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, angular_x, acc_z, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, angular_y, angular_x, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, angular_z, angular_y, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, time_stamp, angular_z, 0),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, IMUInfo, isStamp, time_stamp, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, USensorForward, isStamp, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, IMUInfo, USensorDownward, USensorForward, 0),
    PB_FIELD( 12, BYTES   , OPTIONAL, CALLBACK, OTHER, IMUInfo, piCamImage, USensorDownward, 0),
    PB_FIELD( 13, INT32   , OPTIONAL, STATIC  , OTHER, IMUInfo, imageWidth, piCamImage, 0),
    PB_FIELD( 14, INT32   , OPTIONAL, STATIC  , OTHER, IMUInfo, imageHeight, imageWidth, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
